apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp
spec:
  selector:
    matchLabels:
      app: mynodeapp
  replicas: 2
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: rupadas/sample-node-app:latest
        ports:
        - containerPort: 3037
